name: API Build

on:
  pull_request:
    branches:
      - grad-release
      - main
    paths:
      - 'api/**'
jobs:
  quality_profile:

    runs-on: ubuntu-20.04

    defaults:
      run:
        working-directory: api

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: 18
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-5Jun-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-5Jun-
      - name: Run unit tests
        run: mvn -f pom.xml clean package
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.2.5
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
      - name: Run Sonar Analysis
        run: mvn sonar:sonar
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.host.url=${{ vars.SONAR_HOST_URL }}
          -Dsonar.organization=${{ vars.SONAR_ORG }}
          -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
